using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading.Tasks;

using NSwagTsSplitter.Configuration;
using NSwagTsSplitter.Extensions;
using NSwagTsSplitter.Models;

namespace NSwagTsSplitter.IO;

public class FileWriter
{
    private readonly GeneratorOption _option;
    private readonly List<TsModuleModel> _modules;

    /// <summary>
    /// 
    /// </summary>
    public FileWriter(GeneratorOption option)
    {
        _option = option;
        _modules = new List<TsModuleModel>();
    }

    public void AddModules(ICollection<TsModuleModel> modules)
    {
        _modules.AddRange(modules);
    }
    public async Task WriteAsync()
    {
        foreach (var tsModuleModel in _modules)
        {
            var encode = new UTF8Encoding(false);
            var fullPath = Path.Combine(_option.OutputBaseDirectory, tsModuleModel.ModulePath);
            var folderPath = Path.GetDirectoryName(fullPath);
            if (folderPath == null)
            {
                continue;
            }
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            if (string.IsNullOrWhiteSpace(tsModuleModel.ModuleContent))
            {
                continue;
            }
            // 添加生成日期到头部
            tsModuleModel.ModuleContent = $"// Generated by NSwagTsSplitter at {DateTime.Now:yyyy-MM-dd HH:mm:ss}" + _option.NewLineBehavior + tsModuleModel.ModuleContent;
            // 添加Disable lint 到头部
            tsModuleModel.ModuleContent = _option.DisabledLintLines.JoinAsString(_option.NewLineBehavior) + _option.NewLineBehavior + tsModuleModel.ModuleContent;
            await File.WriteAllTextAsync(fullPath, tsModuleModel.ModuleContent, encode);
        }
    }
}